resources:
  pipelines:
    {{DATA_PRODUCT_ID}}:
      name: {{DATA_PRODUCT_NAME}}
      serverless: true
      catalog: ${var.catalog}
      schema: ${var.schema}
      libraries:
        - glob:
            include: ../src/**
      configuration:
        bundle.sourcePath: ${workspace.file_path}/src
